### ISSUE TITLE
Error : importing external CSS styles

### ISSUE THREAD

**Issue by maximovj** [axllent/mailpit#388] opened 2024-11-16 23:02 UTC
# Error : importing external CSS styles

I am working with HTML and Bootstrap v5 to send an email and display Bootstrap v5 CSS styles, but `mailpit` cannot load the Bootstrap styles correctly. The same issue occurs with emails sent from Laravel.

In the HTML Source tab, I can see the code in more detail, but in the HTML tab, the Bootstrap 5 styles are not applied correctly. I have tried adding the --block-remote-css-and-fonts flag as per the official documentation to fix the issue, but the problem persists.

This is the tab: HTML Source
![image](https://github.com/user-attachments/assets/210b9ad7-65d9-477a-85e6-08d7e06db4d5)

This is the tab: HTML Source
![image](https://github.com/user-attachments/assets/52a02c1e-d98f-4495-bdca-d3565304549d)

This is the expected result:
![image](https://github.com/user-attachments/assets/e207c005-4fc3-45b6-a707-25150a96b1cc)

**Comment by axllent** [comment] 2024-11-16 23:24
It should be working as-is because remote CSS is not blocked by default. Can you please attach a sample message (which I can feed into my Mailpit) to test? Thanks.

**Comment by maximovj** [comment] 2024-11-16 23:55
This is a test message I am making.
[message-test.txt](https://github.com/user-attachments/files/17788269/message-test.txt)

I noticed that this error appears in the browser console, it could be the issue.
![image](https://github.com/user-attachments/assets/d7dbe05a-7a5c-4eb8-838c-c9f332f43e2d)

I am currently using Laravel 8.x and PHP 7.4.33 from Laragon, as shown in the image.
![image](https://github.com/user-attachments/assets/bb9aa8d1-7c2c-4973-a104-f49991692f81)

I did one last test, now in MailHog, and it works correctly when viewing the HTML.
![image](https://github.com/user-attachments/assets/b1cae3a1-d4ec-4cf0-bc00-8c7dcf328281)

**Comment by axllent** [comment] 2024-11-17 02:11
Bug confirmed - leave this with me!

**Comment by axllent** [comment] 2024-11-17 05:01
Thanks for reporting this bug - it's actually been broken for several months so I'm surprised nobody reported it earlier! The fix has been fixed in [v1.21.4](https://github.com/axllent/mailpit/releases/tag/v1.21.4). Please let me know if it is working again for you? Thanks.

**Comment by maximovj** [comment] 2024-11-17 05:25
I ran two tests using version [`v1.21.4`](https://github.com/axllent/mailpit/releases/tag/v1.21.4), and the issue was successfully resolved. 
Cool, bro, it works.

This is test number one
![image](https://github.com/user-attachments/assets/ac4518ab-7b18-49d6-9508-faee85f2cd2c)

This is test number two
![image](https://github.com/user-attachments/assets/1bcfa3f5-684b-4787-a7b2-35a9acb7764c)

**Comment by axllent** [comment] 2024-11-17 06:17
Perfect, thanks for testing and the quick confirmation! 

Regarding using external stylesheets (in general), please note that external CSS files is not the recommended approach as popular web clients like Gmail do not support it. And of those that do,  most do not support modern CSS like bootstrap (so some features may not work). If you're going to be using it, then keep in mind that there will be a significant portion of users who will not have any styling applied.

I'll close this issue now. Thanks again for reporting it!

**Closed** 2024-11-17 06:17 UTC
Labels: bug
