### ISSUE TITLE
Mailpit in crashloopbackoff error in Kubernetes

### ISSUE THREAD

**Issue by wali97** [axllent/mailpit#401] opened 2024-12-09 05:30 UTC
Hi,
I've deployed mailpit as a deployment in my GKE cluster with following configuration,no authentication or anything is enabled,

```
 env:
        - name: MP_DATABASE
          value: /data/mailpit.db
        - name: MP_MAX_MESSAGES
          value: '5000'
        - name: MP_SMTP_AUTH_ACCEPT_ANY
          value: '1'
        - name: MP_SMTP_AUTH_ALLOW_INSECURE
          value: '1'
```

It runs for sometime,but then mailpit pod goes into crashloopbackoff error
`level=fatal msg="database is locked (5) (SQLITE_BUSY)"`

I tried using three different mailpit docker images with version v1.20.7,v1.21.3,v1.21.5 but all result in same error. 
Can please help me out on this as to why i keep getting this error.

**Comment by axllent** [comment] 2024-12-09 06:32
Hi @wali97. Internally Mailpit enforces [single connection](https://github.com/axllent/mailpit/blob/develop/internal/storage/database.go#L98-L100) to the database to prevent this very issue, so this should not happen unless:
1. You have another process sharing / accessing the database (eg: another instance of Mailpit or script reading/writing to the database)
2. The database is stored on a network filesystem such as SMB or NFS (SQLite is designed for local)

Can you confirm you don't have 1 or 2 above, and any other details about your setup that may be appropriate? Are you receiving  a very high load of emails (not that it should matter, I've tested with a constant stream of 130k emails without issues).

**Comment by wali97** [comment] 2024-12-09 07:31
Hi @axllent .
No other process is sharing or accessing the database,i've other instance of mailpit running but they're in a different namesapce..
However,i'm using a NFS server as a persistent storage to store the data at path: /data

**Comment by axllent** [comment] 2024-12-09 07:57
I'm not sure what to say. SQLite over NFS is known for file locking issues, sure it may work for a while, but it goes wrong eventually as you've discovered, not to mention poor performance.

You could investigate NFS mount options (not sure if there are actual working configurations), but it's best to avoid it if possible. Not sure what other options you have though... I would suggest using an elite database, however it also uses SQLite, and it sounds like you may just be shifting the problem.

**Comment by axllent** [comment] 2024-12-09 09:14
Sorry, I just edited my previous response (typo + add link to rqlite).

**Comment by axllent** [comment] 2024-12-09 09:20
I see GKE supports [persistent volumes](https://cloud.google.com/kubernetes-engine/docs/concepts/persistent-volumes) which may solve your issue (by not using NFS).

**Comment by axllent** [comment] 2024-12-10 09:26
I have [updated the documentation](https://mailpit.axllent.org/docs/configuration/email-storage/) to emphasize (more) the fact that the database should be local. Sorry, I wish I could help but there isn't anything else I can do here, so I am closing this ticket.

**Closed by axllent** 2024-12-10 09:26 UTC

**Comment by boomam** [comment] 2025-04-01 19:40
Seeing this issue as well.  
Is there a workaround for this, to have mailpit ignore the storage type in use?

**Comment by axllent** [comment] 2025-04-01 21:37
@boomam Can you please confirm your Mailpit version is >= v1.23.0? SQLite not not designed for NFS (it will always be prone to network delays etc), however it _should_ work if WAL support is disabled.

**Comment by boomam** [comment] 2025-04-01 21:51
Hi,
Running latest release as of today.
I'm aware of the documented limitations of SQLite and network share protocols, but there are use cases.

The WAL option didn't make a difference, error persisted.  

Thanks.

**Comment by axllent** [comment] 2025-04-02 02:50
Unfortunately I'm not sure there is anything I can do about this. The NFS issue is documented and is a known limitation of any SQLite over NFS (this is definitely not limited to Mailpit). A potential work-around has been suggested (`MP_DISABLE_WAL=true`) or using [persistent volumes](https://cloud.google.com/kubernetes-engine/docs/concepts/persistent-volumes) (I never got a response so I don't know 100% if that works), and lastly an alternative approach by using rqlite (although that may fall into the same trap if using NFS).

Unless someone knowledgeable of the issue and a working solution can assist me, I don't know what else I can do, sorry.

**Comment by boomam** [comment] 2025-04-02 02:57
I think there may be a misunderstanding as to what I'm asking / reporting.

To simplify - the function to disable WAL does not work.

This is not a NFS/SMB issue, nor a platform issue.
But an issue with mailpit reporting locks they don't exist, due to what is being described as a WAL issue.

**Comment by axllent** [comment] 2025-04-02 03:31
> To simplify - the function to disable WAL does not work.

Are you sure it is not disabling WAL though? I can confirm that `MP_DISABLE_WAL=true mailpit` does completely disable WAL here which specifically [sets the SQLite journal](https://github.com/axllent/mailpit/blob/develop/internal/storage/database.go#L122-L133) to `DELETE` instead of `WAL`. It should be easy to detect simply by inspecting the path where the database is being written to: there should not be either a `*.db-shm` or `*.db-wal` file alongside the Mailpit db file (if there is then you may be working with a corrupted database from a previous attempt). Can you please confirm that your database path does not contain either of these files while Mailpit is running?

Can you please also tell me what NFS protocol your mount is using (the `vers=` part in `nfsstat -m`)?

**Comment by wali97** [comment] 2025-04-02 05:32
Hi @axllent @boomam 
I got the mailpit v1.21.3 running without any storage type(NFS or PVC). The only which i did in my setup was i deployed mailpit on nonpreemptive k8s nodes so as to avoid frequent restarts,that's all ....didnt face any issue since then.

**Comment by axllent** [comment] 2025-04-03 02:58
Thank you for that detailed info @boomam. Unfortunately there is general confusion as to what NFS actually means - more specifically whether it is in actual fact NFS itself, or whether it's implying any Network Filesystem (eg: Samba). I'm not 100% sure what the right answer is here when it comes to SQLite (yet). I have tested here in my own network with both NFS and Samba, and I don't get issues on either (with or without the `MP_DISABLE_WAL=true`), so this is tough for me to debug. Let's start with what I know:

1. Mailpit sets the maximum connections to a database to `1` - so at any point Mailpit should only have one "open connection" to the database. SQLite in general is designed this way (single-application use). This in itself should prevent unnecessary file locking errors when run locally. This, together with the `MP_DISABLE_WAL=true` should prevent file locking from happening at all, that is unless something else is locking the file (see next point). SQLite does however lock internally for some actions, such as when dealing with rollback journals.
2. Samba (CIFS) supports native file locking as far as I understand (as part of the client/server communication), which is where I suspect your issue may originate from. It is also heavily dependent on both the server config as well as the client. I see that I use `nobrl` in my client config (which according to the [CIFS documentation](https://www.samba.org/~ab/output/htmldocs/manpages-3/mount.cifs.8.html) is "do not send byte range lock requests to the server") , which may be a clue and an option you could try. Sorry, I don't recall why I use this option as it's been years since I last had to tinker with my configs.

The last point I wanted to clarify if that Mailpit, when run without specifying a database, actually still saves everything to a local randomly-named database in the (typically) `/tmp` directory, which gets deleted again on termination. I'm just stating this to clarify that Mailpit does not store messages in memory, not that it is related to your issue ;-)

If you wouldn't mind adding the `nobrl` option to your mount flags to test, then we can hopefully either rule that out or identify the Samba lock as the cause.

**Comment by axllent** [comment] 2025-04-04 04:09
**NFS**: I think the confusion arises when official documentation refers to issues while running SQLite on a "network filesystem", ie: is that NFS or SMB - or **any** network filesystem. It does not specifically name either, unless of course "network filesystem" implies NFS (which is technically "Network File System").

**Max connections**: You could modify the source code, recompile and run that, however I can tell you now that it is hardcoded to a single thread for a very good reason (and not relating to network filesystems) as this would cause race issues when handling heavy SMTP traffic. I hit this issue early in development.

**nobrl**: As I mentioned before, I can't test your environment, however I was able to replicate the same issue here by removing the `nobrl` flag in my SMB mount options:
```
mailpit -d /mnt/smb/mailpit.db
FATA[2025/04/04 16:45:13] database is locked (5) (SQLITE_BUSY)
```
After reverting the fstab change and remounting the volume Mailpit worked exactly as expected (with and without the `MP_DISABLE_WAL=true`). So I'll double-down on my earlier comment that you will need the `nobrl` mount flag in order to disable the Samba byte locking. This is not a Mailpit limitation, this is a conflict between SMB and SQLite (as well as other databases such as PostgreSQL when storing data over SMB). If I recall correctly I had this file locking issue when just writing LibreOffice documents over SMB.  Searching Google reveals this is a well-documented issue with SMB and various apps, especially SQLite. If you haven't experienced this with your other SQLite apps, then it's likely just a matter of time before they hit the same issue while doing a moderate level reading & writing.

**Comment by boomam** [comment] 2025-04-04 16:40
I wonder how other SQLite apps are getting around this without the `nobrl`...
Anyway, could it be worth adding that particular note/workaround to the docs?

**Comment by axllent** [comment] 2025-04-04 21:48
I suspect other apps read & write far less to the db, or potentially don't use SQL transactions - I don't know for sure.

I'll definitely add it to the documentation once you can confirm the option resolves the issue, thanks.
