### ISSUE TITLE
Docker up failure? "disk I/O error (5386)" mailpit exited with code 1

### ISSUE THREAD

**Issue by epicwhale** [axllent/mailpit#271] opened 2024-03-30 09:17 UTC
Following the docker compose example: https://mailpit.axllent.org/docs/install/docker/

```
    mailpit:
        image: axllent/mailpit:latest
        container_name: mailpit
        volumes:
            - ./data:/data
        ports:
            - 8025:8025
            - 1025:1025
        environment:
            MP_MAX_MESSAGES: 5000
            MP_DATA_FILE: /data/mailpit.db
            MP_SMTP_AUTH_ACCEPT_ANY: 1
            MP_SMTP_AUTH_ALLOW_INSECURE: 1
```

When I up it:

```
docker compose up mailpit
[+] Running 1/0
 ✔ Container mailpit  Created                                                                                                                                                   0.0s 
Attaching to mailpit
mailpit  | time="2024/03/30 09:15:35" level=error msg="disk I/O error (5386)"
mailpit exited with code 1
```

Any pointers to resolving this?

**Comment by epicwhale** [comment] 2024-03-30 09:45
Enabling verbose, I get a:

```
mailpit-1  | time="2024/03/30 09:44:10" level=debug msg="[db] opening database /data/mailpit.db"
mailpit-1  | time="2024/03/30 09:44:10" level=error msg="disk I/O error (5386)"
```

But I can see it has created these successfully:
<img width="209" alt="image" src="https://github.com/axllent/mailpit/assets/670655/30cafcef-7b41-488f-9540-7e3805c65666">

**Comment by axllent** [comment] 2024-03-30 09:58
Hi. Is your `./data`  directory by any chance a remote-mounted filesystem? What host OS are you using?

**Comment by epicwhale** [comment] 2024-03-30 11:18
It's a local file system. Using podman on MacOS if that helps? @axllent

**Comment by axllent** [comment] 2024-03-30 11:50
Yes and no (unfortunately). This appears to be a docker (or in your case podman) issue unrelated to Mailpit from what I can tell (searching Google). There is something going wrong with the mount to your local filesystem (permissions, full file system, storage limits, ownership etc), but I can't tell what. My suggestion would be to Google the error "docker disk I/O error" and you will find plenty of issues and potential causes for you to look into and hopefully find the cause.

Sorry I can't help more. Mailpit's docker images have been downloaded close to 3.5 million times and this is the first report I've seen of this nature, so everything indicates that it is a local issue on your end.

**Comment by epicwhale** [comment] 2024-03-30 11:54
@axllent thanks for the tips, i'll dig into it further! for now disabling the `MP_DATA_FILE` helps during development. I have a feeling this has something to do with wal/shm enabled for the sqlite db, and how podman filesystem on mac virtual machines work. Is there a way to disable the wal/shm for the MP_DATA_FILE?

**Comment by axllent** [comment] 2024-03-30 12:11
Not currently, no. This option was added a whole back for performance reasons, and shouldn't cause issues, but you could be right if the filesystem is treated as a remote filesystem. I know it works on Mac with volumes though, so I assume it should work with local mounts as well.

**Comment by epicwhale** [comment] 2024-03-30 13:16
Switching to volumes did the job! thanks for the prompt help here, really appreciate it! :)

ps - great work with mailpit!

**Comment by axllent** [comment] 2024-03-30 20:02
Thank you. Given that the issues are (I'm almost 100% certain) related to your local filesystem mount, I'll close this issue. If you do come across the actual reason for this then please feel free to re-open it.

**Closed by axllent** 2024-03-30 20:02 UTC
